### ISSUE TITLE
Angabe mehrerer Presets macht Probleme

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedSetBlock#2]
Hi. Du hattest ja letztens die Möglichkeit der Multi-Argumentation der Presets hinzugefügt: da scheint es noch Probleme zu geben - oder ist der Syntax falsch?

`/redblockedit -p test1` => test1 wird ausgeführt
`/redblockedit -p test1 test2` => nur test2 wird ausgeführt
`/redblockedit -p test1 test2 test3` => nichts wird ausgeführt

Alle Presets befinden sich in der gleichen Kategorie. Die Position wurde auch zu Beginn gesetzt.

**Comment by Phoenix616** [comment]
Presets müssen mit einem Komma getrennt werden. Also `/redblockedit -p test1,test2,test3` sollte eigentlich funktionieren.

**Comment by RedstoneFuture** [comment]
Das hat leider auch keine Auswirkung,

**Comment by RedstoneFuture** [comment]
`/redblockedit -p test1,test2` => nichts wird ausgeführt
`/redblockedit -p test1,test2,test3` => nichts wird ausgeführt

Gleiches mit einem ";" als Trenner.

Es gibt auch keine Fehlermeldungen in der Console.

**Comment by RedstoneFuture** [comment]
Vielleicht kannst du dir das die Tage kurz mal ansehen. Dann kann ich da weiterarbeiten. :)

**Comment by Phoenix616** [comment]
Sollte jetzt gehen. Kp. wie ich das übersehen hab, bin mir eigentlich sicher dass ich das getestet hatte und das es ging? Vllt. hab ich dass irgendwie nicht committed nach dem Testen :S
