### ISSUE TITLE
"/rbe -p" mit Verlaufs-ID

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedSetBlock#5]
Was hältst du von der Idee ein `/rbe -pid=<id> <preset>` anzubieten?

Damit bin ich nicht immer nur auf die letzte Position beschränkt und kann als Spieler mehrere Chat-Menüs parallel verwenden.

Ich würde dann mit "tellraw" + `{"action":"run_command","value":"/rbe -pid=%id% ItemRemover,Signal-0"}` arbeiten können, wobei immer die jeweilige ID ist. Die ID kann dabei ruhig eine Zufalls-Zahl sein, und ist weiterhin abhängig vom Spieler.

Ich habe jetzt länger drüber nachgedacht und denke, dass es das sinnvollste Verfahren ist, ohne dass die Spieler in anderen Welten die Commands der Chat-Menüs nutzen können und dennoch mehrere parallel verwenden dürfen.

Hier nochmal zusammengefasst ein Demonstration-Video meines Vorhabens:
https://redstoneworld.de/videos/intern/RedCommandSystem-Idee_ID.mp4

**Wichtig** ist hierbei wohl noch, dass weiterhin auch die Welt abgefragt wird. Also hat am besten jede %id% seine eigene Welt. In den Commands kann man ja schlecht die Welt direkt hinterlegen. Momentan fragt er ja bei `/rbe -p <preset>` die Welt ab und vergleicht es mit der Welt, in der `/rbe setpos <X> <Y> <Z>` ausgeführt wurde.

Ich hoffe, diese Funktion ist nicht allzu aufwendig. Es ist aber auch nur erstmal eine Idee.

**Comment by RedstoneFuture** [comment]
Memo an mich:

Test 1: so wie im Video

Test 2: mit 2 bis 3 verschiedenen Welten -> muss jeweils eine Fehlermeldung kommen und die andere funktioniert

Test 3: das Gleiche mit mehreren Spielern

**Comment by RedstoneFuture** [comment]
Notiz fürs Protokoll:

![grafik](https://user-images.githubusercontent.com/4140635/95131244-052baa00-075e-11eb-9625-e71b2b12043a.png)

**Comment by RedstoneFuture** [comment]
Ich sehe da gerade kleine Schwierigkeiten:

1. `-p` und `-pid` ist technisch getrennt - somit muss ich für ein Chat-Menü jeweils 2 x Position setzen:

`/redblockedit setpos %blockx% %blocky% %blockz%` in RedAction für den tellraw-Befehl (**Anzeigen des Chat-Menüs**) +
`/redblockedit setpos %blockx% %blocky% %blockz% -pid%id%` in RedAction oder Chest-GUI für den im Chat-Menü enthaltenen Befehl (**letztendliches Signalstärke des Blockes ändern**)

Bei meinem Konzept dachte ich damals eher an so eine Art History-ID. Oder anders gesagt: jeder neue `-p` hat je Spieler und ggf. je Welt seine eigene PID.

2. Es gibt in RedCommandSystem keinen Placeholder, der den aktuellen `%pid%` anzeigen kann. Darum kann ich in den tellraw Befehlen für Chat-Menüs nur `%rcs-random%` nutzen - was unpraktisch ist (siehe Punkt 1). RedCommandSystem weiß ja nicht, welche PID ich in RedAction definiert habe.

**Comment by RedstoneFuture** [comment]
1. gefixt mit `%pid%` (auch: `%positionid%`)
2. gefixt mit `-p` = `-pid=#SELF` (auch: `-pid=<playername>:#SELF`)

**Comment by RedstoneFuture** [comment]
Also nur zum Abgleich:

Wenn ich in RedAction `/redblockedit setpos %blockx% %blocky% %blockz%` nutze, ist in meinem Test bei RedCommandSystem `%pid%` = `RedstoneFuture:#SELF` .

Wenn ich in RedAction `/redblockedit setpos %blockx% %blocky% %blockz% -pid=15` nutze, ist bei RedCommandSystem `%pid%` = `RedstoneFuture:15` .

Das soll laut Code so sein, ja? Sieht für mich auch richtig aus und würde meiner Meinung nach funktionieren.

**Comment by Phoenix616** [comment]
Ja, so soll das sein.

**Comment by RedstoneFuture** [comment]
Ich hab aktuell noch ein Problem. Schaue dir mal die verlinke PDF an:

[Aufteilung der Module.pdf](https://github.com/RedstoneWorld/RedCommandSystem/files/6015837/Aufteilung.der.Module.pdf)


Wichtig ist vor allem das orange. Ich kann kein Selbstaufruf via `tellraw` realisieren, wenn ich nicht weiß wie die PID lautet, die zu der bereits gesetzten Position gehört. Warum: weil ich ja die RedCommandSystem Befehle via GUI ausführe.

Ich bräuchte vielleicht sowas, wie ein `-pid=#LAST`. `-pid=#SELF` hilft in dem Moment nicht, weil dann ja die ID immer nur `RedstoneFuture:#SELF` ist. Ich brauch aber die zuletzt definierte ID des Spielers.

Oder ich hab irgendwas nicht bedacht? Ich hoffe, die Darstellung in der PDF hilft etwas.

**Comment by Phoenix616** [comment]
Du müsstest halt die pid vom Anfang immer weiter an die anderen Befehle übergeben (also in der GUI) damit die Position dann am Ende benutzbar ist.

Also in deinem Beispiel `/redblockedit -p Chatmenu_Kesse -pid=%pid%` verwenden. (Und halt die Variable irgendwie an die GUI übergeben damit sie in den Befehlen der GUI irgendwie genutzt werden können)

**Comment by RedstoneFuture** [comment]
Man könnte im Chatsystem die PID mit der PlaceholderAPI abrufen. Ansonsten wäre `-pid=#LAST` meine 2. Idee. Ich nutze momentan "DeluxeMenus" für die GUIs und wüsste nicht, dass man irgendwie anders Informationen in die GUI übergeben kann.

**Comment by Phoenix616** [comment]
Klingt irgendwie umständlich und ungenau (da ja die PID nicht direkt von dem ersten Befehlsaufruf genommen wird). Beim Aufrufen der GUI wird die pid ja durch den `-pid` Parameter schon auf einen Zufälligen Wert festgelegt, du kannst also diesen Wert dann an die GUI übergeben und in der GUI in den Befehlen nutzen. (Oder kann die GUI keine Befehls-definierten Variablen/Parameter? Wenn das der Fall ist wäre das natürlich ungünstig und sollte am Besten direkt dort hinzugefügt werden)

**Comment by RedstoneFuture** [comment]
Ich denke, das Plugin kann das nicht. Aber ich frag mal nach.

**Comment by RedstoneFuture** [comment]
Ich glaube es geht .. ich teste gleich was

**Comment by RedstoneFuture** [comment]
Jop, funktioniert! :)
https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/gui#args

Das Feature war sehr versteckt. Aber DeluxeMenus kann das tatsächlich.
